name       : minigalaxy
version    : 1.2.1
release    : 9
source     :
    - https://github.com/sharkwouter/minigalaxy/archive/refs/tags/1.2.1.tar.gz : 680f24248e1235459c1de1d127ea6c642a752ced8b9d2e14b2b168db093a9f48
license    : GPL-3.0-or-later
homepage   : https://sharkwouter.github.io/minigalaxy
component  : games
summary    : A simple GOG client for Linux that lets you download and play your GOG Linux games
description: |
    Log in with your GOG account, download linux games you own on GOG, and launch them. Additionally select what language to download your games in, change where they're installed, search your library, show all or only installed games, view error messages if a game fails to launch, display FPS in games, and use the system's Scummvm or Dosbox installation. Languages supported include English, Dutch, French, German, Polish, Taiwanese Mandarin, and Turkish.
rundeps    :
    - libwebkit-gtk
    - python-gobject
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
