name       : minigalaxy
version    : 0.9.3
release    : 1
source     :
    - https://github.com/sharkwouter/minigalaxy/archive/0.9.3.tar.gz : 8a6baf259f2c1508085a18fe3f30c2071817d67b601385e4c6b51025abd3d9cb
license    : GPL-3.0-or-later
component  : games
summary    : A simple GOG client for Linux that lets you download and play your GOG Linux games
description: |
    Log in with your GOG account, download linux games you own on GOG, and launch them. Additionally select what language to download your games in, change where they're installed, search your library, show all or only installed games, view error messages if a game fails to launch, display FPS in games, and use the system's Scummvm or Dosbox installation. Languages supported include English, Dutch, French, German, Polish, Taiwanese Mandarin, and Turkish.
rundeps    :
    - python-requests
    - python-gobject
    - libwebkit-gtk
build      : |
    %python3_setup
install    : |
    %python3_install
